# Generated by Django 6.0 on 2025-12-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialprojapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
